[package]
name = "swap_min_max"
version = "0.1.0"
authors = ["vlad <volynvlad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
